"""create initial tables

Revision ID: 983d92f3f3f3
Revises: 
Create Date: 2025-07-02 22:20:50.704162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '983d92f3f3f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('completed', 'failed', 'in_progress', name='status').create(op.get_bind())
    op.create_table('file',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('status', postgresql.ENUM('completed', 'failed', 'in_progress', name='status', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batch',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('completed', 'failed', 'in_progress', name='status', create_type=False), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batch')
    op.drop_table('file')
    sa.Enum('completed', 'failed', 'in_progress', name='status').drop(op.get_bind())
    # ### end Alembic commands ###
